# -*- coding: utf-8 -*-
"""data.viz..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vX81SxeG_souDrvBCnx-3UxVzBGd4XPt
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_csv("dataset.csv")

df.head(10)

df.info()

df.isnull().sum()

"""Visualize the data (so that people like me can understand!)"""

plt.figure(figsize=(14,7))
sns.countplot(x=df["isVirus"])

plt.figure(figsize=(14,7))
sns.swarmplot(x=df['isVirus'], y=df['feature_1'])

plt.figure(figsize=(14,7))
sns.swarmplot(x=df['isVirus'], y=df['feature_2'])

plt.figure(figsize=(14,7))
sns.swarmplot(x=df['isVirus'], y=df['feature_3'])

"""Clean up the data (balance it out, impute missing values and so on... depending on the method you are going to use!)"""

df.dropna()

df.sample(10)

df.info()

"""Visualize the cleaned data (so that people like me can understand the effect of cleaning process!)"""

plt.figure(figsize=(14,7))
sns.countplot(x=df["isVirus"])

"""Create a simple model that performs reasonably well."""



"""Evaluate the model with a testset you will create from the dataset."""

